spring:
  application:
    name: zuul-server
  
server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:ks/eureka.p12
    key-store-password: megatravel
    key-alias: eureka
    key-password: megatravel
    trust-store: classpath:ks/tseureka.p12
    trust-store-password: megatravel
    trust-store-type: PKCS12
   
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    serviceUrl:
      defaultZone: https://eureka:admin@localhost:8443/eureka/
    register-with-eureka: false
    fetch-registry: true
    healthcheck:
      enabled: true 
  instance:
      nonSecurePortEnabled: false
      securePortEnabled: true

zuul:
  routes:
    main-backend:
      path: /main-backend/**
      stripPrefix: true
      sensitive-headers:
      - Cookie, Set-Cookie
      serviceId: main-backend
    client-registration-service:
      path: /client-registration-service/**
      stripPrefix: true
      serviceId: client-registration-service
    login-service:
      path: /login-service/**
      stripPrefix: true
      serviceId: login-service
    agent-backend:
      path: /agent-backend/**
      stripPrefix: true
      sensitive-headers:
      - Cookie, Set-Cookie
      serviceId: agent-backend
    agent-creation-service:
      path: /agent-creation-service/**
      stripPrefix: true
      serviceId: agent-creation-service      
  ssl-hostname-validation-enabled: true
    
ribbon:
  secure-ports:
  - 8445
  - 8446
  - 8448
  - 8449
  - 8450 
  eureka:
    enabled: true


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        