spring:
  application:
    name: main-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maindb?useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect#  jackson:#    default-property-inclusion: NON_NULL
    
server:
  port: 8445
  ssl:
    key-store: classpath:store/main-backend.jks
    key-alias: main-backend
    key-store-type: JKS
    key-store-password: megatravel
    key-password: megatravel
#    client-auth: need
    trust-store: classpath:store/main-backend.jks
    trust-store-password: megatravel
    trust-store-type: JKS
    
  error:    whitelabel:      enabled: false 
# security.require-ssl=true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://localhost:8440/eureka/
  instance:
    hostname: localhost    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: 'https://${eureka.instance.hostname}:${server.port}/info'
    healthCheckUrl: 'https://${eureka.instance.hostname}:${server.port}/health'
    homePageUrl: 'https://${eureka.instance.hostname}:${server.port}/'

logging:  file: main-backend.log  level:    root: info
  pattern:    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
    file: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

spring.jackson.default-property-inclusion: NON_NULL
