//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 02:14:56 PM CEST 
//


package com.megatravel.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateCommentResponse }
     * 
     */
//    public CreateCommentResponse createCreateCommentResponse() {
//        return new CreateCommentResponse();
//    }

    /**
     * Create an instance of {@link CreateAccommodationResponse }
     * 
     */
//    public CreateAccommodationResponse createCreateAccommodationResponse() {
//        return new CreateAccommodationResponse();
//    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
//    public SendMessageResponse createSendMessageResponse() {
//        return new SendMessageResponse();
//    }

    /**
     * Create an instance of {@link AccommodationCategory }
     * 
     */
//    public AccommodationCategory createAccommodationCategory() {
//        return new AccommodationCategory();
//    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
//    public Reservation createReservation() {
//        return new Reservation();
//    }

    /**
     * Create an instance of {@link Accommodation }
     * 
//     */
//    public Accommodation createAccommodation() {
//        return new Accommodation();
//    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
//    public AccommodationType createAccommodationType() {
//        return new AccommodationType();
//    }

    /**
     * Create an instance of {@link PriceInSeason }
     * 
//     */
//    public PriceInSeason createPriceInSeason() {
//        return new PriceInSeason();
//    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
//    public Agent createAgent() {
//        return new Agent();
//    }
//
//    /**
//     * Create an instance of {@link Cancelation }
//     * 
//     */
//    public Cancelation createCancelation() {
//        return new Cancelation();
//    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
//    public Administrator createAdministrator() {
//        return new Administrator();
//    }
//
//    /**
//     * Create an instance of {@link EndUser }
//     * 
//     */
//    public EndUser createEndUser() {
//        return new EndUser();
//    }
//
//    /**
//     * Create an instance of {@link CreateReservationRequest }
//     * 
//     */
//    public CreateReservationRequest createCreateReservationRequest() {
//        return new CreateReservationRequest();
//    }
//
//    /**
//     * Create an instance of {@link Message }
//     * 
//     */
//    public Message createMessage() {
//        return new Message();
//    }
//
//    /**
//     * Create an instance of {@link AdditionalServices }
//     * 
//     */
//    public AdditionalServices createAdditionalServices() {
//        return new AdditionalServices();
//    }
//
//    /**
//     * Create an instance of {@link Comment }
//     * 
//     */
//    public Comment createComment() {
//        return new Comment();
//    }
//
//    /**
//     * Create an instance of {@link SendMessageRequest }
//     * 
//     */
//    public SendMessageRequest createSendMessageRequest() {
//        return new SendMessageRequest();
//    }
//
//    /**
//     * Create an instance of {@link GetAccommodationCategoryResponse }
//     * 
//     */
//    public GetAccommodationCategoryResponse createGetAccommodationCategoryResponse() {
//        return new GetAccommodationCategoryResponse();
//    }
//
//    /**
//     * Create an instance of {@link CreateAccommodationRequest }
//     * 
//     */
//    public CreateAccommodationRequest createCreateAccommodationRequest() {
//        return new CreateAccommodationRequest();
//    }
//
//    /**
//     * Create an instance of {@link Privileges }
//     * 
//     */
//    public Privileges createPrivileges() {
//        return new Privileges();
//    }
//
//    /**
//     * Create an instance of {@link GetAccommodationCategoryRequest }
//     * 
//     */
//    public GetAccommodationCategoryRequest createGetAccommodationCategoryRequest() {
//        return new GetAccommodationCategoryRequest();
//    }
//
//    /**
//     * Create an instance of {@link GetAccommodationTypeRequest }
//     * 
//     */
//    public GetAccommodationTypeRequest createGetAccommodationTypeRequest() {
//        return new GetAccommodationTypeRequest();
//    }
//
//    /**
//     * Create an instance of {@link ImageResource }
//     * 
//     */
//    public ImageResource createImageResource() {
//        return new ImageResource();
//    }
//
//    /**
//     * Create an instance of {@link GetAccommodationTypeResponse }
//     * 
//     */
//    public GetAccommodationTypeResponse createGetAccommodationTypeResponse() {
//        return new GetAccommodationTypeResponse();
//    }
//
//    /**
//     * Create an instance of {@link CreateReservationResponse }
//     * 
//     */
//    public CreateReservationResponse createCreateReservationResponse() {
//        return new CreateReservationResponse();
//    }
//
//    /**
//     * Create an instance of {@link Address }
//     * 
//     */
//    public Address createAddress() {
//        return new Address();
//    }
//
//    /**
//     * Create an instance of {@link CreateCommentRequest }
//     * 
//     */
//    public CreateCommentRequest createCreateCommentRequest() {
//        return new CreateCommentRequest();
//    }
//
}
